### ISSUE TITLE
Map animation combinator

### ISSUE THREAD

**Issue by rexim** [rexim/beatwave#111]
It just wraps an animation and applies a function on its value.

``` c++
using namespace dsl;

const auto red = uncompressColor(sf::Color::Red);
const auto green = uncompressColor(sf::Color::Green);

Animated<sf::Color> x;

x.animate(map(from(red).to(green).during(2000),
              compressColor));
```

Can pontentially supersede #108 
See also: [util.cpp#L25](https://github.com/rexim/beatwave/blob/5c6eee144f1c195d50c782f7237faebd2ecc8138/src/core/util.cpp#L25)

**Comment by rexim** [comment]
It will allow to implement gamma correction #39 on the DSL level without any template specializations:

``` c++
x.animate(gammaCorrected()
          .from(sf::Color::Red)
          .to(sf::Color::Green)
          .during(2000))
```

Which may effectively perform the actions in the description of the issue.

**Comment by Newlifer** [comment]
So much win!
