### ISSUE TITLE
Never transfer ownership by a raw pointer

### ISSUE THREAD

**Issue by voldyman** [rexim/beatwave#33]
In LinearAnimationBuilder the operator `LinearAnimation<T>*` returns a heap allocated object which isn't deleted hence causing a memory leak.

raw pointers donot represent ownership and by giving away the ownership there is a leak.
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Ri-raw

use `std::unique_ptr` instead.

**Comment by rexim** [comment]
You are making a good point and I completely agree with you. Thanks for filing that!

But, I think that the title of the issue is slightly misleading. I've checked beatwave with valgrind and I didn't find any memory leaks there:

```
==441== LEAK SUMMARY:
==441==    definitely lost: 0 bytes in 0 blocks
==441==    indirectly lost: 0 bytes in 0 blocks
==441==      possibly lost: 0 bytes in 0 blocks
==441==    still reachable: 159,203 bytes in 547 blocks
==441==         suppressed: 0 bytes in 0 blocks
```

This is because all of the animations are always put inside of an [animated object](https://github.com/rexim/beatwave/blob/fbfe385188e098a68b9478b09da518229205d1d4/src/core/animated.hpp#L46) which always wraps them with the unique_ptr.

So let me rename the issue and we are good to go. :)

**Comment by voldyman** [comment]
weird, i checked in clang-tidy 

```
┌─[voldyman@arc:~/Code/beatwave/build on master]
└─> /usr/local/Cellar/llvm/3.8.1/bin/clang-tidy  ../src/**/*.cpp
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
/Users/voldyman/Code/beatwave/src/beatwave/game.cpp:55:29: warning: Potential memory leak [clang-analyzer-cplusplus.NewDeleteLeaks]
    dummy.animate(repeat(2, seq<sf::Vector2f>({
                            ^
/Users/voldyman/Code/beatwave/src/beatwave/game.cpp:56:9: note: Calling 'LinearTransitionBuilder::operator LinearTransition<sf::Vector2<float> > *'
        from(sf::Vector2f(100.0f, 100.0f)).to(sf::Vector2f(200.0f, 200.0f)).during(1000),
        ^
/Users/voldyman/Code/beatwave/src/core/lineartransitionbuilder.hpp:33:16: note: Memory is allocated
        return new LinearTransition<T>(m_initialState, m_transitionTime, m_finalState);
               ^
/Users/voldyman/Code/beatwave/src/beatwave/game.cpp:56:9: note: Returned allocated memory
        from(sf::Vector2f(100.0f, 100.0f)).to(sf::Vector2f(200.0f, 200.0f)).during(1000),
        ^
/Users/voldyman/Code/beatwave/src/beatwave/game.cpp:55:29: note: Potential memory leak
    dummy.animate(repeat(2, seq<sf::Vector2f>({
                            ^
```

it's definitely a memory leak, since all the object is being allocated but never deleted, i am not sure why valgrind doesn't show that.

**Comment by rexim** [comment]
Everything is correct. It is indeed a `potential memory leak`. But not an actual one. :) But for our project to be future-proof we have to avoid any kind of leaks. Even the potential ones. Planned this issue for the next beatwave stream.
