### ISSUE TITLE
Why the state of Animation class returns by value but not reference?

### ISSUE THREAD

**Issue by Newlifer** [rexim/beatwave#71]
Why the state of `Animation` class returns by value but not reference?

``` c++
class Animation
{
    virtual State getCurrentState() const = 0; // <<
};

```

**Comment by rexim** [comment]
Thanks for the question!

I don't see any significant reason to return the state by reference. Animation is a really abstract interface and it can be and do virtually anything. The state is supposed to be consumed by the invoker of the `getCurrentState`. The implementation of the animation interface may never store the current state in memory. It may simply calculate it from something on each invocation of `getCurrentState`. And if `getCurrentState` returned the state by ref, [the ref would outlife the object it refered to](http://rust-lang.org/). And the requirement of not storing the state in the memory wouldn't be possible to fulfil. Also, returning objects by value may also trigger RVO in some cases. Even for [virtual functions](http://stackoverflow.com/a/26284533/2951870).

I hope I answered your question. Please, share your thoughts.

**Comment by rexim** [comment]
It's been 4 days already. I consider this question to be answered. Thanks!
